import React from 'react';
import '@testing-library/jest-dom';
import { Provider } from 'react-redux';
import thunk from 'redux-thunk';
import TestRenderer from 'react-test-renderer';
import {
  legacy_createStore as createStore, combineReducers, applyMiddleware, createAction,
} from '@reduxjs/toolkit';
import App from '../App';
import { weatherReducer, selectCityReducer, selectCity } from '../redux/weather';

const combinedReducers = combineReducers({
  weather: weatherReducer,
  selectedCity: selectCityReducer,
});

const fakeRetrieveWeather = createAction('FETCH_CITY_WEATHERS/fulfilled', (fetchedData) => ({
  payload: fetchedData,
}));

const store = createStore(combinedReducers, applyMiddleware(thunk));

const INITIAL_STATE = [
  {
    queryCost: 1,
    latitude: 55.757,
    longitude: 37.615,
    resolvedAddress: 'Москва, Центральный федеральный округ, Россия',
    address: 'Moscow',
    timezone: 'Europe/Moscow',
    tzoffset: 3,
    days: [
      {
        datetime: '2023-02-15',
        datetimeEpoch: 1676408400,
        tempmax: -2,
        tempmin: -5.6,
        temp: -3.3,
        feelslikemax: -7.2,
        feelslikemin: -11.1,
        feelslike: -9.2,
        dew: -6.8,
        humidity: 76.9,
        precip: 0.3,
        precipprob: 100,
        precipcover: 12.5,
        preciptype: [
          'snow',
        ],
        snow: 0,
        snowdepth: 29.2,
        windgust: 50.4,
        windspeed: 36,
        winddir: 349.7,
        pressure: 1021.5,
        cloudcover: 84.2,
        visibility: 9.4,
        solarradiation: 57.4,
        solarenergy: 5,
        uvindex: 3,
        severerisk: 10,
        sunrise: '07:55:07',
        sunriseEpoch: 1676436907,
        sunset: '17:33:13',
        sunsetEpoch: 1676471593,
        moonphase: 0.82,
        conditions: 'Snow, Partially cloudy',
        description: 'Partly cloudy throughout the day with afternoon snow.',
        icon: 'snow',
        stations: [
          'UUMO',
          'UUWW',
          'UUEE',
        ],
        source: 'comb',
      },
    ],
    stations: {
      UUMO: {
        distance: 29508,
        latitude: 55.5,
        longitude: 37.5,
        useCount: 0,
        id: 'UUMO',
        name: 'UUMO',
        quality: 50,
        contribution: 0,
      },
      UUWW: {
        distance: 24702,
        latitude: 55.65,
        longitude: 37.27,
        useCount: 0,
        id: 'UUWW',
        name: 'UUWW',
        quality: 50,
        contribution: 0,
      },
      UUEE: {
        distance: 26657,
        latitude: 55.97,
        longitude: 37.42,
        useCount: 0,
        id: 'UUEE',
        name: 'UUEE',
        quality: 50,
        contribution: 0,
      },
    },
  },
  {
    queryCost: 1,
    latitude: 51.5064,
    longitude: -0.12721,
    resolvedAddress: 'London, England, United Kingdom',
    address: 'London',
    timezone: 'Europe/London',
    tzoffset: 0,
    days: [
      {
        datetime: '2023-02-15',
        datetimeEpoch: 1676419200,
        tempmax: 14.9,
        tempmin: 1.7,
        temp: 7.5,
        feelslikemax: 14.9,
        feelslikemin: 1.7,
        feelslike: 6.8,
        dew: 4.5,
        humidity: 83,
        precip: 0.5,
        precipprob: 33.3,
        precipcover: 8.33,
        preciptype: [
          'rain',
        ],
        snow: 0,
        snowdepth: 0,
        windgust: 38.2,
        windspeed: 36,
        winddir: 221,
        pressure: 1023.3,
        cloudcover: 75.6,
        visibility: 12.9,
        solarradiation: 69,
        solarenergy: 6,
        uvindex: 3,
        severerisk: 10,
        sunrise: '07:15:02',
        sunriseEpoch: 1676445302,
        sunset: '17:15:07',
        sunsetEpoch: 1676481307,
        moonphase: 0.82,
        conditions: 'Partially cloudy',
        description: 'Partly cloudy throughout the day.',
        icon: 'partly-cloudy-day',
        stations: [
          'EGWU',
          'EGLL',
          'D5621',
          'E4320',
          'EGLC',
        ],
        source: 'comb',
      },
    ],
    stations: {
      EGWU: {
        distance: 20850,
        latitude: 51.55,
        longitude: -0.42,
        useCount: 0,
        id: 'EGWU',
        name: 'EGWU',
        quality: 50,
        contribution: 0,
      },
      EGLC: {
        distance: 12300,
        latitude: 51.5,
        longitude: 0.05,
        useCount: 0,
        id: 'EGLC',
        name: 'EGLC',
        quality: 50,
        contribution: 0,
      },
      EGLL: {
        distance: 22564,
        latitude: 51.48,
        longitude: -0.45,
        useCount: 0,
        id: 'EGLL',
        name: 'EGLL',
        quality: 50,
        contribution: 0,
      },
      D5621: {
        distance: 11192,
        latitude: 51.535,
        longitude: 0.028,
        useCount: 0,
        id: 'D5621',
        name: 'DW5621 Upton Park UK',
        quality: 0,
        contribution: 0,
      },
      E4320: {
        distance: 59494,
        latitude: 52.031,
        longitude: -0.296,
        useCount: 0,
        id: 'E4320',
        name: 'EW4320 Clifton UK',
        quality: 0,
        contribution: 0,
      },
    },
  },
  {
    queryCost: 1,
    latitude: 48.8572,
    longitude: 2.34141,
    resolvedAddress: 'Paris, Île-de-France, France',
    address: 'Paris',
    timezone: 'Europe/Paris',
    tzoffset: 1,
    days: [
      {
        datetime: '2023-02-15',
        datetimeEpoch: 1676415600,
        tempmax: 12.6,
        tempmin: -0.1,
        temp: 5.4,
        feelslikemax: 12.6,
        feelslikemin: -0.1,
        feelslike: 5.1,
        dew: 2.1,
        humidity: 81,
        precip: 0,
        precipprob: 0,
        precipcover: 0,
        preciptype: null,
        snow: 0,
        snowdepth: 0,
        windgust: 18.7,
        windspeed: 9.6,
        winddir: 186.1,
        pressure: 1026.5,
        cloudcover: 58.9,
        visibility: 11.3,
        solarradiation: 34.9,
        solarenergy: 3.1,
        uvindex: 2,
        severerisk: 10,
        sunrise: '07:59:27',
        sunriseEpoch: 1676444367,
        sunset: '18:10:53',
        sunsetEpoch: 1676481053,
        moonphase: 0.82,
        conditions: 'Partially cloudy',
        description: 'Partly cloudy throughout the day.',
        icon: 'partly-cloudy-day',
        stations: [
          'LFPG',
          'LFPV',
          'LFPO',
          'C1292',
          'LFPN',
          'LFPT',
          'LFPB',
        ],
        source: 'comb',
      },
    ],
    stations: {
      LFPG: {
        distance: 22338,
        latitude: 49.02,
        longitude: 2.52,
        useCount: 0,
        id: 'LFPG',
        name: 'LFPG',
        quality: 50,
        contribution: 0,
      },
      LFPV: {
        distance: 14201,
        latitude: 48.77,
        longitude: 2.2,
        useCount: 0,
        id: 'LFPV',
        name: 'LFPV',
        quality: 50,
        contribution: 0,
      },
      LFPO: {
        distance: 14797,
        latitude: 48.73,
        longitude: 2.4,
        useCount: 0,
        id: 'LFPO',
        name: 'LFPO',
        quality: 49,
        contribution: 0,
      },
      C1292: {
        distance: 6957,
        latitude: 48.812,
        longitude: 2.276,
        useCount: 0,
        id: 'C1292',
        name: 'CW1292 Coignieres FR',
        quality: 0,
        contribution: 0,
      },
      LFPN: {
        distance: 20148,
        latitude: 48.75,
        longitude: 2.12,
        useCount: 0,
        id: 'LFPN',
        name: 'LFPN',
        quality: 50,
        contribution: 0,
      },
      LFPT: {
        distance: 35805,
        latitude: 49.1,
        longitude: 2.02,
        useCount: 0,
        id: 'LFPT',
        name: 'LFPT',
        quality: 50,
        contribution: 0,
      },
      LFPB: {
        distance: 14859,
        latitude: 48.97,
        longitude: 2.45,
        useCount: 0,
        id: 'LFPB',
        name: 'LFPB',
        quality: 50,
        contribution: 0,
      },
    },
  },
  {
    queryCost: 1,
    latitude: 30.0443,
    longitude: 31.2353,
    resolvedAddress: 'القاهرة, مصر',
    address: 'Cairo',
    timezone: 'Africa/Cairo',
    tzoffset: 2,
    days: [
      {
        datetime: '2023-02-15',
        datetimeEpoch: 1676412000,
        tempmax: 17.8,
        tempmin: 9,
        temp: 12.7,
        feelslikemax: 17.8,
        feelslikemin: 8.4,
        feelslike: 12.6,
        dew: 5.7,
        humidity: 64.6,
        precip: 0,
        precipprob: 9.5,
        precipcover: 0,
        preciptype: null,
        snow: 0,
        snowdepth: 0,
        windgust: 28.4,
        windspeed: 11.2,
        winddir: 289.5,
        pressure: 1020.8,
        cloudcover: 52.3,
        visibility: 12.1,
        solarradiation: 155.5,
        solarenergy: 13.4,
        uvindex: 7,
        severerisk: 10,
        sunrise: '06:35:24',
        sunriseEpoch: 1676435724,
        sunset: '17:43:27',
        sunsetEpoch: 1676475807,
        moonphase: 0.82,
        conditions: 'Partially cloudy',
        description: 'Partly cloudy throughout the day.',
        icon: 'partly-cloudy-day',
        stations: [
          'HECA',
        ],
        source: 'comb',
      },
    ],
    stations: {
      HECA: {
        distance: 18512,
        latitude: 30.13,
        longitude: 31.4,
        useCount: 0,
        id: 'HECA',
        name: 'HECA',
        quality: 50,
        contribution: 0,
      },
    },
  },
  {
    queryCost: 1,
    latitude: 25.2695,
    longitude: 55.3088,
    resolvedAddress: 'دبي, الإمارات العربية المتحدة',
    address: 'Dubai',
    timezone: 'Asia/Dubai',
    tzoffset: 4,
    days: [
      {
        datetime: '2023-02-15',
        datetimeEpoch: 1676404800,
        tempmax: 34.9,
        tempmin: 21.9,
        temp: 25.7,
        feelslikemax: 32.2,
        feelslikemin: 21.9,
        feelslike: 25.3,
        dew: 10.3,
        humidity: 40.4,
        precip: 0,
        precipprob: 0,
        precipcover: 0,
        preciptype: null,
        snow: 0,
        snowdepth: null,
        windgust: 36,
        windspeed: 20.5,
        winddir: 114,
        pressure: 1013.3,
        cloudcover: 14.7,
        visibility: 13.5,
        solarradiation: 400.5,
        solarenergy: 34.7,
        uvindex: 10,
        severerisk: 10,
        sunrise: '06:53:46',
        sunriseEpoch: 1676429626,
        sunset: '18:12:26',
        sunsetEpoch: 1676470346,
        moonphase: 0.81,
        conditions: 'Clear',
        description: 'Clear conditions throughout the day.',
        icon: 'clear-day',
        stations: [
          'OMSJ',
          'OMDW',
          'OMDB',
          'remote',
          'E1978',
        ],
        source: 'comb',
      },
    ],
    stations: {
      OMSJ: {
        distance: 22297,
        latitude: 25.33,
        longitude: 55.52,
        useCount: 0,
        id: 'OMSJ',
        name: 'OMSJ',
        quality: 49,
        contribution: 0,
      },
      OMDB: {
        distance: 3044,
        latitude: 25.25,
        longitude: 55.33,
        useCount: 0,
        id: 'OMDB',
        name: 'OMDB',
        quality: 49,
        contribution: 0,
      },
      OMDW: {
        distance: 45562,
        latitude: 24.88,
        longitude: 55.17,
        useCount: 0,
        id: 'OMDW',
        name: 'OMDW',
        quality: 49,
        contribution: 0,
      },
      E1978: {
        distance: 14226,
        latitude: 25.142,
        longitude: 55.314,
        useCount: 0,
        id: 'E1978',
        name: 'EW1978 Dubai AE',
        quality: 0,
        contribution: 0,
      },
    },
  },
  {
    queryCost: 1,
    latitude: -1.97575,
    longitude: 30.0318,
    resolvedAddress: 'Kigali, Umujyi Wa Kigali, Rwanda',
    address: 'Kigali',
    timezone: 'Africa/Kigali',
    tzoffset: 2,
    days: [
      {
        datetime: '2023-02-15',
        datetimeEpoch: 1676412000,
        tempmax: 31.1,
        tempmin: 15,
        temp: 22.7,
        feelslikemax: 29.6,
        feelslikemin: 15,
        feelslike: 22.6,
        dew: 11.7,
        humidity: 51.3,
        precip: 0,
        precipprob: 0,
        precipcover: 0,
        preciptype: null,
        snow: 0,
        snowdepth: 0,
        windgust: 14.4,
        windspeed: 22.3,
        winddir: 296.2,
        pressure: 1012.9,
        cloudcover: 54.7,
        visibility: 15.9,
        solarradiation: 184.9,
        solarenergy: 16.1,
        uvindex: 10,
        severerisk: 10,
        sunrise: '06:08:50',
        sunriseEpoch: 1676434130,
        sunset: '18:19:14',
        sunsetEpoch: 1676477954,
        moonphase: 0.82,
        conditions: 'Partially cloudy',
        description: 'Partly cloudy throughout the day.',
        icon: 'partly-cloudy-day',
        stations: [
          'HRYR',
          'remote',
        ],
        source: 'comb',
      },
    ],
    stations: {
      HRYR: {
        distance: 9833,
        latitude: -1.97,
        longitude: 30.12,
        useCount: 0,
        id: 'HRYR',
        name: 'HRYR',
        quality: 45,
        contribution: 0,
      },
    },
  },
  {
    queryCost: 1,
    latitude: 40.4196,
    longitude: -3.69196,
    resolvedAddress: 'Madrid, Comunidad de Madrid, España',
    address: 'Madrid',
    timezone: 'Europe/Madrid',
    tzoffset: 1,
    days: [
      {
        datetime: '2023-02-15',
        datetimeEpoch: 1676415600,
        tempmax: 13,
        tempmin: 5.5,
        temp: 8.4,
        feelslikemax: 13,
        feelslikemin: 3.7,
        feelslike: 7.8,
        dew: 1.8,
        humidity: 64.6,
        precip: 0,
        precipprob: 0,
        precipcover: 0,
        preciptype: null,
        snow: 0,
        snowdepth: 0,
        windgust: 22,
        windspeed: 8.3,
        winddir: 62.6,
        pressure: 1027.4,
        cloudcover: 75.8,
        visibility: 14.7,
        solarradiation: 131.4,
        solarenergy: 11.4,
        uvindex: 6,
        severerisk: 10,
        sunrise: '08:08:47',
        sunriseEpoch: 1676444927,
        sunset: '18:49:39',
        sunsetEpoch: 1676483379,
        moonphase: 0.82,
        conditions: 'Partially cloudy',
        description: 'Partly cloudy throughout the day.',
        icon: 'partly-cloudy-day',
        stations: [
          'LEMD',
          'LEVS',
          'LETO',
          'F7959',
        ],
        source: 'comb',
      },
    ],
    stations: {
      F7959: {
        distance: 25044,
        latitude: 40.502,
        longitude: -3.967,
        useCount: 0,
        id: 'F7959',
        name: 'FW7959 Villanueva Del Pardillo ES',
        quality: 0,
        contribution: 0,
      },
      LEMD: {
        distance: 12495,
        latitude: 40.45,
        longitude: -3.55,
        useCount: 0,
        id: 'LEMD',
        name: 'LEMD',
        quality: 50,
        contribution: 0,
      },
      LEVS: {
        distance: 8668,
        latitude: 40.38,
        longitude: -3.78,
        useCount: 0,
        id: 'LEVS',
        name: 'LEVS',
        quality: 50,
        contribution: 0,
      },
      LETO: {
        distance: 19623,
        latitude: 40.47,
        longitude: -3.47,
        useCount: 0,
        id: 'LETO',
        name: 'LETO',
        quality: 48,
        contribution: 0,
      },
    },
  },
  {
    queryCost: 1,
    latitude: 40.7146,
    longitude: -74.0071,
    resolvedAddress: 'New York, NY, United States',
    address: 'New York',
    timezone: 'America/New_York',
    tzoffset: -5,
    days: [
      {
        datetime: '2023-02-15',
        datetimeEpoch: 1676437200,
        tempmax: 15.6,
        tempmin: 7.4,
        temp: 11.2,
        feelslikemax: 15.6,
        feelslikemin: 6,
        feelslike: 10.7,
        dew: 2.8,
        humidity: 56.5,
        precip: 0,
        precipprob: 6,
        precipcover: 0,
        preciptype: null,
        snow: 0,
        snowdepth: 0,
        windgust: 42.5,
        windspeed: 25.9,
        winddir: 202.1,
        pressure: 1017.6,
        cloudcover: 34.3,
        visibility: 16.1,
        solarradiation: 114.2,
        solarenergy: 9.7,
        uvindex: 4,
        severerisk: 10,
        sunrise: '06:50:14',
        sunriseEpoch: 1676461814,
        sunset: '17:30:42',
        sunsetEpoch: 1676500242,
        moonphase: 0.83,
        conditions: 'Partially cloudy',
        description: 'Partly cloudy throughout the day.',
        icon: 'partly-cloudy-day',
        stations: [
          'KLGA',
          'KJRB',
          'F8726',
          'KNYC',
        ],
        source: 'comb',
      },
    ],
    stations: {
      KLGA: {
        distance: 10937,
        latitude: 40.77,
        longitude: -73.9,
        useCount: 0,
        id: 'KLGA',
        name: 'KLGA',
        quality: 100,
        contribution: 0,
      },
      KJRB: {
        distance: 1644,
        latitude: 40.7,
        longitude: -74.01,
        useCount: 0,
        id: 'KJRB',
        name: 'KJRB',
        quality: 94,
        contribution: 0,
      },
      F8726: {
        distance: 5313,
        latitude: 40.671,
        longitude: -73.981,
        useCount: 0,
        id: 'F8726',
        name: 'FW8726 Brooklyn NY US',
        quality: 0,
        contribution: 0,
      },
      KNYC: {
        distance: 6577,
        latitude: 40.77,
        longitude: -73.98,
        useCount: 0,
        id: 'KNYC',
        name: 'KNYC',
        quality: 100,
        contribution: 0,
      },
    },
  },
  {
    queryCost: 1,
    latitude: 41.9032,
    longitude: 12.4957,
    resolvedAddress: 'Roma, Lazio, Italia',
    address: 'Roma',
    timezone: 'Europe/Rome',
    tzoffset: 1,
    days: [
      {
        datetime: '2023-02-15',
        datetimeEpoch: 1676415600,
        tempmax: 17.6,
        tempmin: -0.3,
        temp: 7.9,
        feelslikemax: 17.6,
        feelslikemin: -2.3,
        feelslike: 7.4,
        dew: 3.1,
        humidity: 74.8,
        precip: 0,
        precipprob: 0,
        precipcover: 0,
        preciptype: null,
        snow: 0,
        snowdepth: 0,
        windgust: 15.8,
        windspeed: 7.8,
        winddir: 78,
        pressure: 1029.5,
        cloudcover: 20.7,
        visibility: 14.7,
        solarradiation: 156.4,
        solarenergy: 13.5,
        uvindex: 6,
        severerisk: 10,
        sunrise: '07:06:23',
        sunriseEpoch: 1676441183,
        sunset: '17:42:34',
        sunsetEpoch: 1676479354,
        moonphase: 0.82,
        conditions: 'Partially cloudy',
        description: 'Partly cloudy throughout the day.',
        icon: 'partly-cloudy-day',
        stations: [
          'LIRF',
          'LIRE',
          'LIRU',
          'AT416',
          'LIRA',
        ],
        source: 'comb',
      },
    ],
    stations: {
      LIRF: {
        distance: 24847,
        latitude: 41.8,
        longitude: 12.23,
        useCount: 0,
        id: 'LIRF',
        name: 'LIRF',
        quality: 50,
        contribution: 0,
      },
      LIRE: {
        distance: 28709,
        latitude: 41.65,
        longitude: 12.43,
        useCount: 0,
        id: 'LIRE',
        name: 'LIRE',
        quality: 48,
        contribution: 0,
      },
      LIRU: {
        distance: 5222,
        latitude: 41.95,
        longitude: 12.5,
        useCount: 0,
        id: 'LIRU',
        name: 'LIRU',
        quality: 23,
        contribution: 0,
      },
      AT416: {
        distance: 13531,
        latitude: 41.787,
        longitude: 12.448,
        useCount: 0,
        id: 'AT416',
        name: 'IK0AOC Rome IT',
        quality: 0,
        contribution: 0,
      },
      LIRA: {
        distance: 12339,
        latitude: 41.8,
        longitude: 12.55,
        useCount: 0,
        id: 'LIRA',
        name: 'LIRA',
        quality: 50,
        contribution: 0,
      },
    },
  },
];

describe('Test pure functions', () => {
  test('App Component should render correctly', () => {
    const tree = TestRenderer.create(
      <Provider store={store}>
        <App />
      </Provider>,
    ).toJSON();
    expect(tree).toMatchSnapshot();
  });

  test('Test redux store weather information default case', () => {
    const currentState = store.getState();
    expect(currentState.weather).toEqual([]);
  });

  test('Test redux store selected city', () => {
    const currentSelected = store.getState().selectedCity;
    expect(currentSelected).toBeNull();
  });

  test('Test selectedCity', () => {
    store.dispatch(selectCity('Kigali'));
    const currentSelected = store.getState().selectedCity;
    expect(currentSelected).toEqual('Kigali');
  });

  test('Test fakeRetrieveWeather', () => {
    store.dispatch(fakeRetrieveWeather(INITIAL_STATE));
    const currentWeatherInfo = store.getState().weather;
    expect(currentWeatherInfo).toEqual(INITIAL_STATE);
  });
});
